spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://125.177.127.112:8806/dblog?serverTimezone=UTC
      username: bloger
      password: a123456789

mybatis:
  configuration:
    map-underscore-to-camel-case: true

---
spring:
  profiles: hyuni

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.219.157:3306/dblog?serverTimezone=UTC

---
spring:
  profiles: deploy

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/dblog?serverTimezone=UTC
